name: RoguePlugin
version: 1.0
main: TomDang.example.roguePlugin.RoguePlugin
api-version: "1.21"

commands:
  rogueping:
    description: Test command
    usage: /rogueping

  start:
    description:
    Start a roguelike run (phase 1: just state)
    usage: /start

  lobby:
    description:
    Leave your run and return to lobby (phase 1: just state)
    usage: /lobby

  run:
    description: Show your current run status
    usage: /run

  stats:
    description: View and modify player stats
    usage: /stats

  mobstick:
    description: Gives a Mob Inspector stick
    usage: /mobstick

  mobtag:
    description: Tag the mob you're looking at with a template + level (testing)
    usage: /mobtag <template> [level]
